import {useState} from "react";
import {useQuery,useQueryClient} from "@tanstack/react-query";
import apiClient from "../services/apiClient.js";
import {useAuth} from "../auth/authContext.js";
const blank={label:"",recipientName:"",phone:"",address:""};
export default function AccountPage(){
 const {user,refresh}=useAuth();const client=useQueryClient();const [name,setName]=useState(user.name);
 const [password,setPassword]=useState({currentPassword:"",password:"",confirmation:""});const [address,setAddress]=useState(blank);const [editing,setEditing]=useState(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
 const profile=useQuery({queryKey:["account"],queryFn:async()=>(await apiClient.get("/api/account")).data});
 const addresses=useQuery({queryKey:["addresses"],queryFn:async()=>(await apiClient.get("/api/account/addresses")).data});
 async function run(action){setBusy(true);setError("");setMessage("");try{await action();}catch(e){setError(e.response?.data?.message||Object.values(e.response?.data||{})[0]||"Unable to save changes.");}finally{setBusy(false);}}
 return <section className="space-y-6"><h1 className="text-3xl font-bold">My account</h1>{error&&<p role="alert" className="field-error">{error}</p>}{message&&<p role="status" className="bg-green-50 p-3 text-green-800">{message}</p>}
 <div className="grid gap-6 lg:grid-cols-2"><form className="panel space-y-4 p-6" onSubmit={e=>{e.preventDefault();run(async()=>{await apiClient.put("/api/account",{name});await refresh();setMessage("Profile updated.");});}}><h2 className="text-xl font-bold">Profile</h2><p className="break-words text-sm">{user.email}</p><label className="field-label" htmlFor="account-name">Name</label><input id="account-name" className="field-input" required maxLength={255} value={name} onChange={e=>setName(e.target.value)}/><button className="btn-primary" disabled={busy}>Save profile</button></form>
 <form className="panel space-y-4 p-6" onSubmit={e=>{e.preventDefault();if(password.password!==password.confirmation){setError("Passwords do not match.");return;}run(async()=>{await apiClient.post("/api/account/password",password);setPassword({currentPassword:"",password:"",confirmation:""});setMessage("Password changed. Other sessions will be signed out.");});}}><h2 className="text-xl font-bold">Change password</h2>{profile.isError?<p role="alert">Unable to load account. <button type="button" onClick={()=>profile.refetch()}>Retry</button></p>:profile.data?.googleAccount?<p>Manage your password through your Google account.</p>:<>{[['currentPassword','Current password'],['password','New password'],['confirmation','Confirm new password']].map(([key,label])=><div key={key}><label className="field-label" htmlFor={`account-${key}`}>{label}</label><input id={`account-${key}`} className="field-input" type="password" autoComplete={key==="currentPassword"?"current-password":"new-password"} required minLength={key==="currentPassword"?1:8} maxLength={72} value={password[key]} onChange={e=>setPassword({...password,[key]:e.target.value})}/></div>)}<button className="btn-primary" disabled={busy||profile.isPending}>Change password</button></>}</form></div>
 <div className="panel space-y-4 p-6"><h2 className="text-xl font-bold">Saved addresses</h2>{addresses.isPending?<p role="status">Loading addresses…</p>:addresses.isError?<p role="alert">Unable to load addresses. <button onClick={()=>addresses.refetch()}>Retry</button></p>:<ul className="divide-y">{addresses.data.map(item=><li key={item.id} className="space-y-2 py-4"><p className="font-bold">{item.label}</p><p>{item.recipientName} · {item.phone}</p><p className="break-words">{item.address}</p><div className="flex gap-3"><button className="btn-outline" disabled={busy} onClick={()=>{setEditing(item.id);setAddress(item);}}>Edit</button><button className="btn-danger" disabled={busy} onClick={()=>{if(window.confirm("Remove this saved address?"))run(async()=>{await apiClient.delete(`/api/account/addresses/${item.id}`);await client.invalidateQueries({queryKey:["addresses"]});setMessage("Address removed.");});}}>Remove</button></div></li>)}</ul>}
 <form className="space-y-4 border-t pt-4" onSubmit={e=>{e.preventDefault();run(async()=>{if(editing)await apiClient.put(`/api/account/addresses/${editing}`,address);else await apiClient.post("/api/account/addresses",address);setAddress(blank);setEditing(null);await client.invalidateQueries({queryKey:["addresses"]});setMessage("Address saved.");});}}><h3 className="font-bold">{editing?"Edit address":"Add address"}</h3>{[['label','Address label',80],['recipientName','Recipient name',255],['phone','Phone number',25],['address','Full address',500]].map(([key,label,max])=><div key={key}><label className="field-label" htmlFor={`saved-${key}`}>{label}</label><input id={`saved-${key}`} className="field-input" required maxLength={max} minLength={key==="address"?8:1} pattern={key==="phone"?"[+0-9 ()-]{7,25}":undefined} value={address[key]} onChange={e=>setAddress({...address,[key]:e.target.value})}/></div>)}<div className="flex gap-3"><button className="btn-primary" disabled={busy}>Save address</button>{editing&&<button type="button" className="btn-outline" onClick={()=>{setEditing(null);setAddress(blank);}}>Cancel edit</button>}</div></form></div></section>;
}
