ALTER TABLE orders ADD COLUMN fulfilment VARCHAR(20) NULL,
 ADD COLUMN recipient_name VARCHAR(255) NULL,
 ADD COLUMN phone VARCHAR(25) NULL,
 ADD COLUMN address VARCHAR(500) NULL,
 ADD COLUMN delivery_fee DECIMAL(10,2) NULL;
